typography_spectrum: 0.9308456748794987
color:
  brandStrength: 0.07080143007689553
  lightness: 0.23494109606600858
  saturation: 0.7450238102702147
  rhythmicContrast: 0.6284102480732237
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
github: true
layout_spectrum: 0.021524430095669952
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/91d2659b-6a2e-4458-aaf5-23e053c15329.png
name: inbalance
navigation:
  - name: About us
    id: 1c37a298-b71b-4157-b50d-c323cee49407
    type: content
  - name: Services
    id: fa3659cb-bb42-456a-987c-98e2a8203300
    type: content
  - name: Survay
    url: 'http://survay.io/application/app/31'
    type: external
title: In Balance ADR Group LLC
content: []
description: "Human Resources and Conflict Mitigation Solutions\_"
purpose:
  - type: contact
    url: 'tel:877-360-2464'
    label: Call 877-360-2464
